FROM python:3.9-slim



WORKDIR /app



RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir \

  tensorflow==2.19.0 \

  anvil-uplink==0.3.36 \

  numpy



COPY tx_uplink_server.py /app/



ENV PYTHONUNBUFFERED=1

CMD ["python", "tx_uplink_server.py"]

